// Package models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package models

import (
	"time"
)

// Booking defines model for Booking.
type Booking struct {
	CheckInTs  *time.Time `json:"check_in_ts,omitempty"`
	CheckOutTs *time.Time `json:"check_out_ts,omitempty"`
	Guests     *int       `json:"guests,omitempty"`
	Id         int        `json:"id"`
	RoomId     int        `json:"room_id"`
}

// BookingCreateRequest defines model for BookingCreateRequest.
type BookingCreateRequest struct {
	CheckInTs  time.Time `json:"check_in_ts"`
	CheckOutTs time.Time `json:"check_out_ts"`
	Guests     *int      `json:"guests,omitempty"`
	RoomId     int       `json:"room_id"`
}

// BookingUpdateRequest defines model for BookingUpdateRequest.
type BookingUpdateRequest struct {
	CheckInTs  time.Time `json:"check_in_ts"`
	CheckOutTs time.Time `json:"check_out_ts"`
	Guests     *int      `json:"guests,omitempty"`
	RoomId     int       `json:"room_id"`
}

// Cleaner defines model for Cleaner.
type Cleaner struct {
	Id      int    `json:"id"`
	Name    string `json:"name"`
	Surname string `json:"surname"`
}

// CleanerCreateRequest defines model for CleanerCreateRequest.
type CleanerCreateRequest struct {
	Name    string `json:"name"`
	Surname string `json:"surname"`
}

// CleanerOrder defines model for CleanerOrder.
type CleanerOrder struct {
	CleanerId int `json:"cleaner_id"`
	Id        int `json:"id"`
	OrderId   int `json:"order_id"`
}

// CleanerOrderCreateRequest defines model for CleanerOrderCreateRequest.
type CleanerOrderCreateRequest struct {
	CleanerId int `json:"cleaner_id"`
}

// CleanerUpdateRequest defines model for CleanerUpdateRequest.
type CleanerUpdateRequest struct {
	Name    *string `json:"name,omitempty"`
	Surname *string `json:"surname,omitempty"`
}

// CleaningOrder defines model for CleaningOrder.
type CleaningOrder struct {
	BookingId    int        `json:"booking_id"`
	CleaningTs   *time.Time `json:"cleaning_ts,omitempty"`
	CleaningType *string    `json:"cleaning_type,omitempty"`
	Cost         int        `json:"cost"`
	Done         *bool      `json:"done,omitempty"`
	Id           int        `json:"id"`
	Notes        *string    `json:"notes,omitempty"`
}

// CleaningOrderCreateRequest defines model for CleaningOrderCreateRequest.
type CleaningOrderCreateRequest struct {
	BookingId    int       `json:"booking_id"`
	CleaningTs   time.Time `json:"cleaning_ts"`
	CleaningType *string   `json:"cleaning_type,omitempty"`
	Cost         int       `json:"cost"`
	Done         *bool     `json:"done,omitempty"`
	Notes        *string   `json:"notes,omitempty"`
}

// CleaningOrderUpdateRequest defines model for CleaningOrderUpdateRequest.
type CleaningOrderUpdateRequest struct {
	BookingId    int       `json:"booking_id"`
	CleaningTs   time.Time `json:"cleaning_ts"`
	CleaningType *string   `json:"cleaning_type,omitempty"`
	Cost         int       `json:"cost"`
	Done         *bool     `json:"done,omitempty"`
	Notes        *string   `json:"notes,omitempty"`
}

// Room defines model for Room.
type Room struct {
	Desc  *string `json:"desc,omitempty"`
	Floor int     `json:"floor"`
	Id    int     `json:"id"`
}

// RoomCreateRequest defines model for RoomCreateRequest.
type RoomCreateRequest struct {
	Desc  *string `json:"desc,omitempty"`
	Floor int     `json:"floor"`
}

// RoomUpdateRequest defines model for RoomUpdateRequest.
type RoomUpdateRequest struct {
	Desc  *string `json:"desc,omitempty"`
	Floor *int    `json:"floor,omitempty"`
}

// PostBookingsJSONRequestBody defines body for PostBookings for application/json ContentType.
type PostBookingsJSONRequestBody = BookingCreateRequest

// PutBookingsIdJSONRequestBody defines body for PutBookingsId for application/json ContentType.
type PutBookingsIdJSONRequestBody = BookingUpdateRequest

// PostCleanersJSONRequestBody defines body for PostCleaners for application/json ContentType.
type PostCleanersJSONRequestBody = CleanerCreateRequest

// PutCleanersIdJSONRequestBody defines body for PutCleanersId for application/json ContentType.
type PutCleanersIdJSONRequestBody = CleanerUpdateRequest

// PostCleaningOrdersJSONRequestBody defines body for PostCleaningOrders for application/json ContentType.
type PostCleaningOrdersJSONRequestBody = CleaningOrderCreateRequest

// PutCleaningOrdersIdJSONRequestBody defines body for PutCleaningOrdersId for application/json ContentType.
type PutCleaningOrdersIdJSONRequestBody = CleaningOrderUpdateRequest

// PostCleaningOrdersIdCleanersJSONRequestBody defines body for PostCleaningOrdersIdCleaners for application/json ContentType.
type PostCleaningOrdersIdCleanersJSONRequestBody = CleanerOrderCreateRequest

// PostRoomsJSONRequestBody defines body for PostRooms for application/json ContentType.
type PostRoomsJSONRequestBody = RoomCreateRequest

// PutRoomsIdJSONRequestBody defines body for PutRoomsId for application/json ContentType.
type PutRoomsIdJSONRequestBody = RoomUpdateRequest
