-- +goose Up
-- +goose StatementBegin
-- Заказы и исполнители
CREATE TABLE "cleaners&orders" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"cleaner_id" INTEGER NOT NULL,
	"order_id" INTEGER NOT NULL,
	PRIMARY KEY("id")
);

-- Уборщики
CREATE TABLE "cleaners" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(255) NOT NULL,
	"surname" VARCHAR(255) NOT NULL,
	PRIMARY KEY("id")
);

-- Номера
CREATE TABLE "rooms" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"floor" INTEGER NOT NULL,
	"desc" VARCHAR(255),
	PRIMARY KEY("id")
);

-- Бронирования
CREATE TABLE "bookings" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"room_id" INTEGER NOT NULL,
	"check_in_ts" TIMESTAMP NOT NULL DEFAULT NOW(),
	"check_out_ts" TIMESTAMP NOT NULL DEFAULT NOW(),
	"guests" INTEGER NOT NULL DEFAULT 2,
	PRIMARY KEY("id")
);

-- Заказы на уборку
CREATE TABLE "cleaning_orders" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"booking_id" INTEGER NOT NULL,
	"cleaning_type" VARCHAR(255) NOT NULL DEFAULT 'periodic',
	"cleaning_ts" TIMESTAMP NOT NULL DEFAULT NOW(),
	"notes" VARCHAR(255),
	"cost" INTEGER NOT NULL,
	"done" BOOLEAN DEFAULT false,
	PRIMARY KEY("id")
);

-- Отношения
ALTER TABLE "cleaners&orders"
ADD FOREIGN KEY("cleaner_id") REFERENCES "cleaners"("id")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "bookings"
ADD FOREIGN KEY("room_id") REFERENCES "rooms"("id")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "cleaners&orders"
ADD FOREIGN KEY("order_id") REFERENCES "cleaning_orders"("id")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "cleaning_orders"
ADD FOREIGN KEY("booking_id") REFERENCES "bookings"("id")
ON UPDATE CASCADE ON DELETE CASCADE;

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS "cleaners&orders", "cleaners", "rooms", "bookings", "cleaning_orders";
-- +goose StatementEnd